theme: jekyll-theme-cayman
title: ["Fire Together Wire Together: A Dynamic Pruning Approach with Self-Supervised Mask Prediction"]
description: ["Sara Elkerdawy, Mostafa Elhoushi, Hong Zhang, Nilanjan Ray"]
markdown:           kramdown
kramdown:
    math_engine:    katex
