theme: jekyll-theme-cayman
title: ["Fire Together Wire Together"]
description: ["A Dynamic Pruning Approach with Self-Supervised Mask Prediction"]
markdown:           kramdown
kramdown:
    math_engine:    katex
